# Site settings
title: Human Action # site title
description: This blog is dedicated to summarizing and analyzing <b>Human Action</b> by Ludwig von Mises, a cornerstone of Austrian economics. We break down its key ideas and insights into easily digestible articles.
lang: en-US # default lang
timezone: Asia/Tehran # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/piharpi/jekyll-klise # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Ludwig von Mises # author name
  bio: This blog is dedicated to summarizing and analyzing <b>Human Action</b> by Ludwig von Mises, a cornerstone of Austrian economics. We break down its key ideas and insights into easily digestible articles.
  username: Eman # general username
  github: EmanAmini # github username
  twitter: AminiEman # twitter username
#  facebook: facebook_username # facebook username
#  email: your-email@email.com # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://HumanAction.ilola.ir" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
